export const TEST_DISPATCH = "TEST_DISPATCH";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_DRIVER = "SET_CURRENT_DRIVER";
export const GET_LOCATION = "GET_LOCATION";
